name: Stage MkDocs Site

on:
  workflow_dispatch:

jobs:
  stage:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material

      - name: Build site
        run: mkdocs build -f src/mkdocs.yml -d site_build

      - name: Deploy to /staged
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          rm -rf staged
          mv ../site_build staged
          git add staged
          git commit -m "Stage build from $GITHUB_SHA" || echo "No changes"
          git push origin gh-pages
