name: Stage MkDocs Site

on:
  workflow_dispatch:

jobs:
  stage:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material

      - name: Build site
        run: mkdocs build -f src/mkdocs.yml -d site_build

      - name: Deploy to /staged
        run: |
          repo_url=$(git config --get remote.origin.url)
          tmp_dir=$(mktemp -d)

          git clone --branch gh-pages --single-branch "$repo_url" "$tmp_dir"

          rm -rf "$tmp_dir/staged"
          mkdir -p "$tmp_dir/staged"
          cp -r site_build/* "$tmp_dir/staged/"

          cd "$tmp_dir"
          git add staged
          git commit -m "Stage build from $GITHUB_SHA" || echo "No changes"
          git push origin gh-pages
